apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dockersampleconfig
  template:
    metadata:
      labels:
        app: Dockersampleconfig
    spec:
      containers:
      - name: sureshcrr
        image: sureshcrr.azurecr.io/sureshrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: sureshconfig

---
apiVersion: v1
kind: Service
metadata:
  name: dockersampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Dockersampleconfig
